package com.zzvc.mmps.alert.model;

// Generated 2011-4-13 11:13:04 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AlertConfig generated by hbm2java
 */
@Entity
@Table(name = "alert_config")
public class AlertConfig implements java.io.Serializable {

	private long id;
	private String configKey;
	private String configValue;

	public AlertConfig() {
	}

	public AlertConfig(long id, String configKey, String configValue) {
		this.id = id;
		this.configKey = configKey;
		this.configValue = configValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "config_key", nullable = false)
	public String getConfigKey() {
		return this.configKey;
	}

	public void setConfigKey(String configKey) {
		this.configKey = configKey;
	}

	@Column(name = "config_value", nullable = false)
	public String getConfigValue() {
		return this.configValue;
	}

	public void setConfigValue(String configValue) {
		this.configValue = configValue;
	}

}
