package com.zzvc.mmps.alert.model;

// Generated 2011-4-20 15:33:58 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlayerAlert generated by hbm2java
 */
@Entity
@Table(name = "player_alert")
public class PlayerAlert extends AlertBaseEntity implements java.io.Serializable {

	private String address;
	private Date lastHeartbeat;

	public PlayerAlert() {
	}

	public PlayerAlert(long id) {
		this.id = id;
	}

	public PlayerAlert(long id, String address, Date lastHeartbeat,
			Boolean active, Date ariseTime, Date recoverTime, Boolean mailed) {
		this.id = id;
		this.address = address;
		this.lastHeartbeat = lastHeartbeat;
		this.active = active;
		this.ariseTime = ariseTime;
		this.recoverTime = recoverTime;
		this.mailSend = mailed;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_heartbeat", length = 23)
	public Date getLastHeartbeat() {
		return this.lastHeartbeat;
	}

	public void setLastHeartbeat(Date lastHeartbeat) {
		this.lastHeartbeat = lastHeartbeat;
	}

}
