package com.zzvc.mmps.alert.model;

// Generated 2011-7-11 11:44:27 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlayerLastingFaultAlert generated by hbm2java
 */
@Entity
@Table(name = "player_lasting_fault_alert")
public class PlayerLastingFaultAlert extends AlertBaseEntity implements java.io.Serializable {

	private String address;
	private Date lastHeartbeat;

	public PlayerLastingFaultAlert() {
	}

	public PlayerLastingFaultAlert(long id) {
		this.id = id;
	}

	public PlayerLastingFaultAlert(long id, String address, Date lastHeartbeat,
			Boolean active, Date ariseTime, Date recoverTime, Boolean mailed, Boolean smsSend) {
		this.id = id;
		this.address = address;
		this.lastHeartbeat = lastHeartbeat;
		this.active = active;
		this.ariseTime = ariseTime;
		this.recoverTime = recoverTime;
		this.mailSend = mailed;
		this.smsSend = smsSend;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_heartbeat", length = 23)
	public Date getLastHeartbeat() {
		return this.lastHeartbeat;
	}

	public void setLastHeartbeat(Date lastHeartbeat) {
		this.lastHeartbeat = lastHeartbeat;
	}

}
