package com.zzvc.mmps.alert.model;

// Generated 2011-7-11 11:44:27 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ServerAlert generated by hbm2java
 */
@Entity
@Table(name = "server_alert")
public class ServerAlert extends AlertBaseEntity implements java.io.Serializable {

	private String code;
	private Date lastHeartbeat;

	public ServerAlert() {
	}

	public ServerAlert(long id) {
		this.id = id;
	}

	public ServerAlert(long id, String code, Date lastHeartbeat,
			Boolean active, Date ariseTime, Date recoverTime, Boolean mailed, Boolean smsSend) {
		this.id = id;
		this.code = code;
		this.lastHeartbeat = lastHeartbeat;
		this.active = active;
		this.ariseTime = ariseTime;
		this.recoverTime = recoverTime;
		this.mailSend = mailed;
		this.smsSend = smsSend;
	}

	@Column(name = "code")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_heartbeat", length = 23)
	public Date getLastHeartbeat() {
		return this.lastHeartbeat;
	}

	public void setLastHeartbeat(Date lastHeartbeat) {
		this.lastHeartbeat = lastHeartbeat;
	}

}
